using Newtonsoft.Json;
using System;
using System.Collections.Generic;
namespace NiceShot.Core.Models.Entities{
public class em_bal_common_v1{
public long id {get;set;}
public string secucode {get;set;}
public string security_code {get;set;}
public DateTime? report_date {get;set;}
public DateTime? notice_date {get;set;}
public DateTime? update_date {get;set;}
public decimal? accept_deposit_interbank {get;set;}
public decimal? accounts_payable {get;set;}
public decimal? accounts_rece {get;set;}
public decimal? accrued_expense {get;set;}
public decimal? advance_receivables {get;set;}
public decimal? agent_trade_security {get;set;}
public decimal? agent_underwrite_security {get;set;}
public decimal? amortize_cost_finasset {get;set;}
public decimal? amortize_cost_finliab {get;set;}
public decimal? amortize_cost_ncfinasset {get;set;}
public decimal? amortize_cost_ncfinliab {get;set;}
public decimal? appoint_fvtpl_finasset {get;set;}
public decimal? appoint_fvtpl_finliab {get;set;}
public decimal? asset_balance {get;set;}
public decimal? asset_other {get;set;}
public decimal? assign_cash_dividend {get;set;}
public decimal? available_sale_finasset {get;set;}
public decimal? bond_payable {get;set;}
public decimal? borrow_fund {get;set;}
public decimal? buy_resale_finasset {get;set;}
public decimal? capital_reserve {get;set;}
public decimal? cip {get;set;}
public decimal? consumptive_biological_asset {get;set;}
public decimal? contract_asset {get;set;}
public decimal? contract_liab {get;set;}
public decimal? convert_diff {get;set;}
public decimal? creditor_invest {get;set;}
public decimal? current_asset_balance {get;set;}
public decimal? current_asset_other {get;set;}
public decimal? current_liab_balance {get;set;}
public decimal? current_liab_other {get;set;}
public decimal? defer_income {get;set;}
public decimal? defer_income_1year {get;set;}
public decimal? defer_tax_asset {get;set;}
public decimal? defer_tax_liab {get;set;}
public decimal? derive_finasset {get;set;}
public decimal? derive_finliab {get;set;}
public decimal? develop_expense {get;set;}
public decimal? div_holdsale_asset {get;set;}
public decimal? div_holdsale_liab {get;set;}
public decimal? dividend_payable {get;set;}
public decimal? dividend_rece {get;set;}
public decimal? equity_balance {get;set;}
public decimal? equity_other {get;set;}
public decimal? export_refund_rece {get;set;}
public decimal? fee_commission_payable {get;set;}
public decimal? fin_fund {get;set;}
public decimal? finance_rece {get;set;}
public decimal? fixed_asset {get;set;}
public decimal? fixed_asset_disposal {get;set;}
public decimal? fvtoci_finasset {get;set;}
public decimal? fvtoci_ncfinasset {get;set;}
public decimal? fvtpl_finasset {get;set;}
public decimal? fvtpl_finliab {get;set;}
public decimal? general_risk_reserve {get;set;}
public decimal? goodwill {get;set;}
public decimal? hold_maturity_invest {get;set;}
public decimal? holdsale_asset {get;set;}
public decimal? holdsale_liab {get;set;}
public decimal? insurance_contract_reserve {get;set;}
public decimal? intangible_asset {get;set;}
public decimal? interest_payable {get;set;}
public decimal? interest_rece {get;set;}
public decimal? internal_payable {get;set;}
public decimal? internal_rece {get;set;}
public decimal? inventory {get;set;}
public decimal? invest_realestate {get;set;}
public decimal? lease_liab {get;set;}
public decimal? lend_fund {get;set;}
public decimal? liab_balance {get;set;}
public decimal? liab_equity_balance {get;set;}
public decimal? liab_equity_other {get;set;}
public decimal? liab_other {get;set;}
public decimal? loan_advance {get;set;}
public decimal? loan_pbc {get;set;}
public decimal? long_equity_invest {get;set;}
public decimal? long_loan {get;set;}
public decimal? long_payable {get;set;}
public decimal? long_prepaid_expense {get;set;}
public decimal? long_rece {get;set;}
public decimal? long_staffsalary_payable {get;set;}
public decimal? minority_equity {get;set;}
public decimal? monetaryfunds {get;set;}
public decimal? noncurrent_asset_1year {get;set;}
public decimal? noncurrent_asset_balance {get;set;}
public decimal? noncurrent_asset_other {get;set;}
public decimal? noncurrent_liab_1year {get;set;}
public decimal? noncurrent_liab_balance {get;set;}
public decimal? noncurrent_liab_other {get;set;}
public decimal? note_accounts_payable {get;set;}
public decimal? note_accounts_rece {get;set;}
public decimal? note_payable {get;set;}
public decimal? note_rece {get;set;}
public decimal? oil_gas_asset {get;set;}
public decimal? other_compre_income {get;set;}
public decimal? other_creditor_invest {get;set;}
public decimal? other_current_asset {get;set;}
public decimal? other_current_liab {get;set;}
public decimal? other_equity_invest {get;set;}
public decimal? other_equity_other {get;set;}
public decimal? other_equity_tool {get;set;}
public decimal? other_noncurrent_asset {get;set;}
public decimal? other_noncurrent_finasset {get;set;}
public decimal? other_noncurrent_liab {get;set;}
public decimal? other_payable {get;set;}
public decimal? other_rece {get;set;}
public decimal? parent_equity_balance {get;set;}
public decimal? parent_equity_other {get;set;}
public decimal? perpetual_bond {get;set;}
public decimal? perpetual_bond_paybale {get;set;}
public decimal? predict_current_liab {get;set;}
public decimal? predict_liab {get;set;}
public decimal? preferred_shares {get;set;}
public decimal? preferred_shares_paybale {get;set;}
public decimal? premium_rece {get;set;}
public decimal? prepayment {get;set;}
public decimal? productive_biology_asset {get;set;}
public decimal? project_material {get;set;}
public decimal? rc_reserve_rece {get;set;}
public decimal? reinsure_payable {get;set;}
public decimal? reinsure_rece {get;set;}
public decimal? sell_repo_finasset {get;set;}
public decimal? settle_excess_reserve {get;set;}
public decimal? share_capital {get;set;}
public decimal? short_bond_payable {get;set;}
public decimal? short_fin_payable {get;set;}
public decimal? short_loan {get;set;}
public decimal? special_payable {get;set;}
public decimal? special_reserve {get;set;}
public decimal? staff_salary_payable {get;set;}
public decimal? subsidy_rece {get;set;}
public decimal? surplus_reserve {get;set;}
public decimal? tax_payable {get;set;}
public decimal? total_assets {get;set;}
public decimal? total_current_assets {get;set;}
public decimal? total_current_liab {get;set;}
public decimal? total_equity {get;set;}
public decimal? total_liab_equity {get;set;}
public decimal? total_liabilities {get;set;}
public decimal? total_noncurrent_assets {get;set;}
public decimal? total_noncurrent_liab {get;set;}
public decimal? total_other_payable {get;set;}
public decimal? total_other_rece {get;set;}
public decimal? total_parent_equity {get;set;}
public decimal? trade_finasset {get;set;}
public decimal? trade_finasset_notfvtpl {get;set;}
public decimal? trade_finliab {get;set;}
public decimal? trade_finliab_notfvtpl {get;set;}
public decimal? treasury_shares {get;set;}
public decimal? unassign_rpofit {get;set;}
public decimal? unconfirm_invest_loss {get;set;}
public decimal? useright_asset {get;set;}
public string opinion_type {get;set;}
}}
