using Newtonsoft.Json;
using System;
using System.Collections.Generic;
namespace NiceShot.Core.Models.Entities{
public class em_balancesheet_bank{
public long id {get;set;}
public string securitycode {get;set;}
public int reporttype {get;set;}
public int reportdatetype {get;set;}
public int type {get;set;}
public DateTime? reportdate {get;set;}
public string currency {get;set;}
public decimal? cashanddepositcbank {get;set;}
public decimal? depositinfi {get;set;}
public decimal? preciousmetal {get;set;}
public decimal? lendfund {get;set;}
public decimal? fvaluefasset {get;set;}
public decimal? tradefasset {get;set;}
public decimal? definefvaluefasset {get;set;}
public decimal? derivefasset {get;set;}
public decimal? buysellbackfasset {get;set;}
public decimal? accountrec {get;set;}
public decimal? interestrec {get;set;}
public decimal? loanadvances {get;set;}
public decimal? saleablefasset {get;set;}
public decimal? heldmaturityinv {get;set;}
public decimal? investrec {get;set;}
public decimal? ltequityinv {get;set;}
public decimal? invsubsidiary {get;set;}
public decimal? invjoint {get;set;}
public decimal? estateinvest {get;set;}
public decimal? fixedasset {get;set;}
public decimal? constructionprogress {get;set;}
public decimal? intangibleasset {get;set;}
public decimal? goodwill {get;set;}
public decimal? masset {get;set;}
public decimal? massetdevalue {get;set;}
public decimal? netmasset {get;set;}
public decimal? deferincometaxasset {get;set;}
public decimal? otherasset {get;set;}
public decimal? sumasset {get;set;}
public decimal? borrowfromcbank {get;set;}
public decimal? fideposit {get;set;}
public decimal? borrowfund {get;set;}
public decimal? fvaluefliab {get;set;}
public decimal? tradefliab {get;set;}
public decimal? definefvaluefliab {get;set;}
public decimal? derivefliab {get;set;}
public decimal? sellbuybackfasset {get;set;}
public decimal? acceptdeposit {get;set;}
public decimal? outwardremittance {get;set;}
public decimal? cdandbillrec {get;set;}
public decimal? cd {get;set;}
public decimal? salarypay {get;set;}
public decimal? taxpay {get;set;}
public decimal? interestpay {get;set;}
public decimal? dividendpay {get;set;}
public decimal? anticipateliab {get;set;}
public decimal? deferincometaxliab {get;set;}
public decimal? bondpay {get;set;}
public decimal? preferstocbond {get;set;}
public decimal? sustainbond {get;set;}
public decimal? juniorbondpay {get;set;}
public decimal? otherliab {get;set;}
public decimal? sumliab {get;set;}
public decimal? shequity {get;set;}
public decimal? otherequity {get;set;}
public decimal? preferredstock {get;set;}
public decimal? sustainabledebt {get;set;}
public decimal? otherequityother {get;set;}
public decimal? capitalreserve {get;set;}
public decimal? invrevaluereserve {get;set;}
public decimal? inventoryshare {get;set;}
public decimal? hedgereserve {get;set;}
public decimal? surplusreserve {get;set;}
public decimal? generalriskprepare {get;set;}
public decimal? retainedearning {get;set;}
public decimal? suggestassigndivi {get;set;}
public decimal? diffconversionfc {get;set;}
public decimal? sumparentequity {get;set;}
public decimal? minorityequity {get;set;}
public decimal? sumshequity {get;set;}
public decimal? sumliabshequity {get;set;}
}}
