using Newtonsoft.Json;
using System;
using System.Collections.Generic;
namespace NiceShot.Core.Models.Entities{
public class em_cashflow_broker{
public long id {get;set;}
public string securitycode {get;set;}
public int reporttype {get;set;}
public int reportdatetype {get;set;}
public int type {get;set;}
public DateTime? reportdate {get;set;}
public string currency {get;set;}
public decimal? nidisptradefasset {get;set;}
public decimal? niotherfinainstru {get;set;}
public decimal? intandcommrec {get;set;}
public decimal? uwsecurityrec {get;set;}
public decimal? niborrowfund {get;set;}
public decimal? agenttradesecurityrec {get;set;}
public decimal? buysellbackfassetrec {get;set;}
public decimal? agentuwsecurityrec {get;set;}
public decimal? nibuybackfund {get;set;}
public decimal? nitradesettlement {get;set;}
public decimal? nidirectinv {get;set;}
public decimal? taxreturnrec {get;set;}
public decimal? otheroperaterec {get;set;}
public decimal? sumoperateflowin {get;set;}
public decimal? buysellbackfassetpay {get;set;}
public decimal? nddisptradefasset {get;set;}
public decimal? ndotherfinainstr {get;set;}
public decimal? intandcommpay {get;set;}
public decimal? ndborrowfund {get;set;}
public decimal? employeepay {get;set;}
public decimal? taxpay {get;set;}
public decimal? ndtradesettlement {get;set;}
public decimal? nddirectinv {get;set;}
public decimal? nilendfund {get;set;}
public decimal? ndbuybackfund {get;set;}
public decimal? agenttradesecuritypay {get;set;}
public decimal? otheroperatepay {get;set;}
public decimal? sumoperateflowout {get;set;}
public decimal? netoperatecashflow {get;set;}
public decimal? disposalinvrec {get;set;}
public decimal? nidispsaleablefasset {get;set;}
public decimal? invincomerec {get;set;}
public decimal? dispfilassetrec {get;set;}
public decimal? dispsubsidiaryrec {get;set;}
public decimal? otherinvrec {get;set;}
public decimal? suminvflowin {get;set;}
public decimal? invpay {get;set;}
public decimal? nddispsaleablefasset {get;set;}
public decimal? buyfilassetpay {get;set;}
public decimal? getsubsidiarypay {get;set;}
public decimal? otherinvpay {get;set;}
public decimal? suminvflowout {get;set;}
public decimal? netinvcashflow {get;set;}
public decimal? acceptinvrec {get;set;}
public decimal? subsidiaryaccept {get;set;}
public decimal? loanrec {get;set;}
public decimal? issuebondrec {get;set;}
public decimal? otherfinarec {get;set;}
public decimal? sumfinaflowin {get;set;}
public decimal? repaydebtpay {get;set;}
public decimal? diviprofitorintpay {get;set;}
public decimal? subsidiarypay {get;set;}
public decimal? otherfinapay {get;set;}
public decimal? sumfinaflowout {get;set;}
public decimal? netfinacashflow {get;set;}
public decimal? effectexchangerate {get;set;}
public decimal? nicashequi {get;set;}
public decimal? cashequibeginning {get;set;}
public decimal? cashequiending {get;set;}
}}
