using Newtonsoft.Json;
using System;
using System.Collections.Generic;
namespace NiceShot.Core.Models.Entities{
public class em_inc_common_v1{
public long id {get;set;}
public string secucode {get;set;}
public string security_code {get;set;}
public DateTime? report_date {get;set;}
public DateTime? notice_date {get;set;}
public DateTime? update_date {get;set;}
public decimal? total_operate_income {get;set;}
public decimal? operate_income {get;set;}
public decimal? interest_income {get;set;}
public decimal? earned_premium {get;set;}
public decimal? fee_commission_income {get;set;}
public decimal? other_business_income {get;set;}
public decimal? toi_other {get;set;}
public decimal? total_operate_cost {get;set;}
public decimal? operate_cost {get;set;}
public decimal? interest_expense {get;set;}
public decimal? fee_commission_expense {get;set;}
public decimal? research_expense {get;set;}
public decimal? surrender_value {get;set;}
public decimal? net_compensate_expense {get;set;}
public decimal? net_contract_reserve {get;set;}
public decimal? policy_bonus_expense {get;set;}
public decimal? reinsure_expense {get;set;}
public decimal? other_business_cost {get;set;}
public decimal? operate_tax_add {get;set;}
public decimal? sale_expense {get;set;}
public decimal? manage_expense {get;set;}
public decimal? me_research_expense {get;set;}
public decimal? finance_expense {get;set;}
public decimal? fe_interest_expense {get;set;}
public decimal? fe_interest_income {get;set;}
public decimal? asset_impairment_loss {get;set;}
public decimal? credit_impairment_loss {get;set;}
public decimal? toc_other {get;set;}
public decimal? fairvalue_change_income {get;set;}
public decimal? invest_income {get;set;}
public decimal? invest_joint_income {get;set;}
public decimal? net_exposure_income {get;set;}
public decimal? exchange_income {get;set;}
public decimal? asset_disposal_income {get;set;}
public decimal? asset_impairment_income {get;set;}
public decimal? credit_impairment_income {get;set;}
public decimal? other_income {get;set;}
public decimal? operate_profit_other {get;set;}
public decimal? operate_profit_balance {get;set;}
public decimal? operate_profit {get;set;}
public decimal? nonbusiness_income {get;set;}
public decimal? noncurrent_disposal_income {get;set;}
public decimal? nonbusiness_expense {get;set;}
public decimal? noncurrent_disposal_loss {get;set;}
public decimal? effect_tp_other {get;set;}
public decimal? total_profit_balance {get;set;}
public decimal? total_profit {get;set;}
public decimal? income_tax {get;set;}
public decimal? effect_netprofit_other {get;set;}
public decimal? effect_netprofit_balance {get;set;}
public decimal? unconfirm_invest_loss {get;set;}
public decimal? netprofit {get;set;}
public decimal? precombine_profit {get;set;}
public decimal? continued_netprofit {get;set;}
public decimal? discontinued_netprofit {get;set;}
public decimal? parent_netprofit {get;set;}
public decimal? minority_interest {get;set;}
public decimal? deduct_parent_netprofit {get;set;}
public decimal? netprofit_other {get;set;}
public decimal? netprofit_balance {get;set;}
public decimal? basic_eps {get;set;}
public decimal? diluted_eps {get;set;}
public decimal? other_compre_income {get;set;}
public decimal? parent_oci {get;set;}
public decimal? minority_oci {get;set;}
public decimal? parent_oci_other {get;set;}
public decimal? parent_oci_balance {get;set;}
public decimal? unable_oci {get;set;}
public decimal? creditrisk_fairvalue_change {get;set;}
public decimal? otherright_fairvalue_change {get;set;}
public decimal? setup_profit_change {get;set;}
public decimal? rightlaw_unable_oci {get;set;}
public decimal? unable_oci_other {get;set;}
public decimal? unable_oci_balance {get;set;}
public decimal? able_oci {get;set;}
public decimal? rightlaw_able_oci {get;set;}
public decimal? afa_fairvalue_change {get;set;}
public decimal? hmi_afa {get;set;}
public decimal? cashflow_hedge_valid {get;set;}
public decimal? creditor_fairvalue_change {get;set;}
public decimal? creditor_impairment_reserve {get;set;}
public decimal? finance_oci_amt {get;set;}
public decimal? convert_diff {get;set;}
public decimal? able_oci_other {get;set;}
public decimal? able_oci_balance {get;set;}
public decimal? oci_other {get;set;}
public decimal? oci_balance {get;set;}
public decimal? total_compre_income {get;set;}
public decimal? parent_tci {get;set;}
public decimal? minority_tci {get;set;}
public decimal? precombine_tci {get;set;}
public decimal? effect_tci_balance {get;set;}
public decimal? tci_other {get;set;}
public decimal? tci_balance {get;set;}
public decimal? acf_end_income {get;set;}
public string opinion_type {get;set;}
}}
