using Newtonsoft.Json;
using System;
using System.Collections.Generic;
namespace NiceShot.Core.Models.JsonObjects{
[JsonObject]
public class em_cashflow_bank_jo{
public string SECURITYCODE {get;set;}
public int REPORTTYPE {get;set;}
public int TYPE {get;set;}
public string REPORTDATE {get;set;}
public string NIDEPOSIT {get;set;}
public string NICLIENTDEPOSIT {get;set;}
public string NIFIDEPOSIT {get;set;}
public string NIBORROWFROMCBANK {get;set;}
public string NDDEPOSITINCBANKFI {get;set;}
public string NDDEPOSITINCBANK {get;set;}
public string NDDEPOSITINFI {get;set;}
public string NIBORROWSELLBUYBACK {get;set;}
public string NIBORROWFUND {get;set;}
public string NISELLBUYBACKFASSET {get;set;}
public string NDLENDBUYSELLBACK {get;set;}
public string NDLENDFUND {get;set;}
public string NDBUYSELLBACKFASSET {get;set;}
public string NETCD {get;set;}
public string NITRADEFLIAB {get;set;}
public string NDTRADEFASSET {get;set;}
public string INTANDCOMMREC {get;set;}
public string INTREC {get;set;}
public string COMMREC {get;set;}
public string DISPMASSETREC {get;set;}
public string CANCELLOANREC {get;set;}
public string OTHEROPERATEREC {get;set;}
public string SUMOPERATEFLOWIN {get;set;}
public string NILOANADVANCES {get;set;}
public string NDBORROWFROMCBANK {get;set;}
public string NIDEPOSITINCBANKFI {get;set;}
public string NIDEPOSITINCBANK {get;set;}
public string NIDEPOSITINFI {get;set;}
public string NDFIDEPOSIT {get;set;}
public string NDISSUECD {get;set;}
public string NILENDSELLBUYBACK {get;set;}
public string NILENDFUND {get;set;}
public string NIBUYSELLBACKFASSET {get;set;}
public string NDBORROWSELLBUYBACK {get;set;}
public string NDBORROWFUND {get;set;}
public string NDSELLBUYBACKFASSET {get;set;}
public string NITRADEFASSET {get;set;}
public string NDTRADEFLIAB {get;set;}
public string INTANDCOMMPAY {get;set;}
public string INTPAY {get;set;}
public string COMMPAY {get;set;}
public string EMPLOYEEPAY {get;set;}
public string TAXPAY {get;set;}
public string BUYFINALEASEASSETPAY {get;set;}
public string NIACCOUNTREC {get;set;}
public string OTHEROPERATEPAY {get;set;}
public string SUMOPERATEFLOWOUT {get;set;}
public string NETOPERATECASHFLOW {get;set;}
public string DISPOSALINVREC {get;set;}
public string INVINCOMEREC {get;set;}
public string DIVIORPROFITREC {get;set;}
public string DISPFILASSETREC {get;set;}
public string DISPSUBSIDIARYREC {get;set;}
public string OTHERINVREC {get;set;}
public string SUMINVFLOWIN {get;set;}
public string INVPAY {get;set;}
public string BUYFILASSETPAY {get;set;}
public string GETSUBSIDIARYPAY {get;set;}
public string OTHERINVPAY {get;set;}
public string SUMINVFLOWOUT {get;set;}
public string NETINVCASHFLOW {get;set;}
public string ISSUEBONDREC {get;set;}
public string ISSUEJUNIORBONDREC {get;set;}
public string ISSUEOTHERBONDREC {get;set;}
public string OTHERFINAREC {get;set;}
public string ACCEPTINVREC {get;set;}
public string SUBSIDIARYACCEPT {get;set;}
public string ISSUECD {get;set;}
public string ADDSHARECAPITALREC {get;set;}
public string SUMFINAFLOWIN {get;set;}
public string REPAYDEBTPAY {get;set;}
public string BONDINTPAY {get;set;}
public string ISSUESHAREREC {get;set;}
public string OTHERFINAPAY {get;set;}
public string DIVIPROFITORINTPAY {get;set;}
public string SUMFINAFLOWOUT {get;set;}
public string NETFINACASHFLOW {get;set;}
public string EFFECTEXCHANGERATE {get;set;}
public string NICASHEQUI {get;set;}
public string CASHEQUIBEGINNING {get;set;}
public string CASHEQUIENDING {get;set;}
}}
