using Newtonsoft.Json;
using System;
using System.Collections.Generic;
namespace NiceShot.Core.Models.Entities{
public class em_balancesheet_common{
public long id {get;set;}
public string securitycode {get;set;}
public int reporttype {get;set;}
public int type {get;set;}
public DateTime? reportdate {get;set;}
public decimal? monetaryfund {get;set;}
public decimal? settlementprovision {get;set;}
public decimal? lendfund {get;set;}
public decimal? fvaluefasset {get;set;}
public decimal? tradefasset {get;set;}
public decimal? definefvaluefasset {get;set;}
public decimal? billrec {get;set;}
public decimal? accountrec {get;set;}
public decimal? advancepay {get;set;}
public decimal? premiumrec {get;set;}
public decimal? rirec {get;set;}
public decimal? ricontactreserverec {get;set;}
public decimal? interestrec {get;set;}
public decimal? dividendrec {get;set;}
public decimal? otherrec {get;set;}
public decimal? exportrebaterec {get;set;}
public decimal? subsidyrec {get;set;}
public decimal? internalrec {get;set;}
public decimal? buysellbackfasset {get;set;}
public decimal? inventory {get;set;}
public decimal? clheldsaleass {get;set;}
public decimal? nonlassetoneyear {get;set;}
public decimal? otherlasset {get;set;}
public decimal? sumlasset {get;set;}
public decimal? loanadvances {get;set;}
public decimal? saleablefasset {get;set;}
public decimal? heldmaturityinv {get;set;}
public decimal? ltrec {get;set;}
public decimal? ltequityinv {get;set;}
public decimal? estateinvest {get;set;}
public decimal? fixedasset {get;set;}
public decimal? constructionprogress {get;set;}
public decimal? constructionmaterial {get;set;}
public decimal? liquidatefixedasset {get;set;}
public decimal? productbiologyasset {get;set;}
public decimal? oilgasasset {get;set;}
public decimal? intangibleasset {get;set;}
public decimal? developexp {get;set;}
public decimal? goodwill {get;set;}
public decimal? ltdeferasset {get;set;}
public decimal? deferincometaxasset {get;set;}
public decimal? othernonlasset {get;set;}
public decimal? sumnonlasset {get;set;}
public decimal? sumasset {get;set;}
public decimal? stborrow {get;set;}
public decimal? borrowfromcbank {get;set;}
public decimal? deposit {get;set;}
public decimal? borrowfund {get;set;}
public decimal? fvaluefliab {get;set;}
public decimal? tradefliab {get;set;}
public decimal? definefvaluefliab {get;set;}
public decimal? billpay {get;set;}
public decimal? accountpay {get;set;}
public decimal? advancereceive {get;set;}
public decimal? sellbuybackfasset {get;set;}
public decimal? commpay {get;set;}
public decimal? salarypay {get;set;}
public decimal? taxpay {get;set;}
public decimal? interestpay {get;set;}
public decimal? dividendpay {get;set;}
public decimal? ripay {get;set;}
public decimal? internalpay {get;set;}
public decimal? otherpay {get;set;}
public decimal? anticipatelliab {get;set;}
public decimal? contactreserve {get;set;}
public decimal? agenttradesecurity {get;set;}
public decimal? agentuwsecurity {get;set;}
public decimal? deferincomeoneyear {get;set;}
public decimal? stbondrec {get;set;}
public decimal? clheldsaleliab {get;set;}
public decimal? nonlliaboneyear {get;set;}
public decimal? otherlliab {get;set;}
public decimal? sumlliab {get;set;}
public decimal? ltborrow {get;set;}
public decimal? bondpay {get;set;}
public decimal? preferstocbond {get;set;}
public decimal? sustainbond {get;set;}
public decimal? ltaccountpay {get;set;}
public decimal? ltsalarypay {get;set;}
public decimal? specialpay {get;set;}
public decimal? anticipateliab {get;set;}
public decimal? deferincome {get;set;}
public decimal? deferincometaxliab {get;set;}
public decimal? othernonlliab {get;set;}
public decimal? sumnonlliab {get;set;}
public decimal? sumliab {get;set;}
public decimal? sharecapital {get;set;}
public decimal? otherequity {get;set;}
public decimal? preferredstock {get;set;}
public decimal? sustainabledebt {get;set;}
public decimal? otherequityother {get;set;}
public decimal? capitalreserve {get;set;}
public decimal? inventoryshare {get;set;}
public decimal? specialreserve {get;set;}
public decimal? surplusreserve {get;set;}
public decimal? generalriskprepare {get;set;}
public decimal? unconfirminvloss {get;set;}
public decimal? retainedearning {get;set;}
public decimal? plancashdivi {get;set;}
public decimal? diffconversionfc {get;set;}
public decimal? sumparentequity {get;set;}
public decimal? minorityequity {get;set;}
public decimal? sumshequity {get;set;}
public decimal? sumliabshequity {get;set;}
}}
