using Newtonsoft.Json;
using System;
using System.Collections.Generic;
namespace NiceShot.Core.Models.Entities{
public class em_balancesheet_insurance{
public long id {get;set;}
public string securitycode {get;set;}
public int reporttype {get;set;}
public int reportdatetype {get;set;}
public int type {get;set;}
public DateTime? reportdate {get;set;}
public string currency {get;set;}
public decimal? monetaryfund {get;set;}
public decimal? settlementprovision {get;set;}
public decimal? lendfund {get;set;}
public decimal? fvaluefasset {get;set;}
public decimal? tradefasset {get;set;}
public decimal? definefvaluefasset {get;set;}
public decimal? derivefasset {get;set;}
public decimal? buysellbackfasset {get;set;}
public decimal? interestrec {get;set;}
public decimal? premiumrec {get;set;}
public decimal? rirec {get;set;}
public decimal? ricontactreserverec {get;set;}
public decimal? unduerireserverec {get;set;}
public decimal? claimrireserverec {get;set;}
public decimal? liferireserverec {get;set;}
public decimal? lthealthrireserverec {get;set;}
public decimal? insuredpledgeloan {get;set;}
public decimal? loanadvances {get;set;}
public decimal? gdepositpay {get;set;}
public decimal? creditorplaninv {get;set;}
public decimal? otherrec {get;set;}
public decimal? tdeposit {get;set;}
public decimal? saleablefasset {get;set;}
public decimal? heldmaturityinv {get;set;}
public decimal? investrec {get;set;}
public decimal? accountrec {get;set;}
public decimal? ltequityinv {get;set;}
public decimal? capitalgdepositpay {get;set;}
public decimal? estateinvest {get;set;}
public decimal? fixedasset {get;set;}
public decimal? constructionprogress {get;set;}
public decimal? intangibleasset {get;set;}
public decimal? goodwill {get;set;}
public decimal? deferincometaxasset {get;set;}
public decimal? otherasset {get;set;}
public decimal? independentasset {get;set;}
public decimal? sumasset {get;set;}
public decimal? stborrow {get;set;}
public decimal? fideposit {get;set;}
public decimal? gdepositrec {get;set;}
public decimal? borrowfund {get;set;}
public decimal? fvaluefliab {get;set;}
public decimal? tradefliab {get;set;}
public decimal? definefvaluefliab {get;set;}
public decimal? derivefliab {get;set;}
public decimal? sellbuybackfasset {get;set;}
public decimal? acceptdeposit {get;set;}
public decimal? agenttradesecurity {get;set;}
public decimal? accountpay {get;set;}
public decimal? billpay {get;set;}
public decimal? advancerec {get;set;}
public decimal? premiumadvance {get;set;}
public decimal? commpay {get;set;}
public decimal? ripay {get;set;}
public decimal? salarypay {get;set;}
public decimal? taxpay {get;set;}
public decimal? interestpay {get;set;}
public decimal? dividendpay {get;set;}
public decimal? anticipateliab {get;set;}
public decimal? claimpay {get;set;}
public decimal? policydivipay {get;set;}
public decimal? otherpay {get;set;}
public decimal? insureddepositinv {get;set;}
public decimal? contactreserve {get;set;}
public decimal? unduereserve {get;set;}
public decimal? claimreserve {get;set;}
public decimal? lifereserve {get;set;}
public decimal? lthealthreserve {get;set;}
public decimal? ltborrow {get;set;}
public decimal? bondpay {get;set;}
public decimal? preferstocbond {get;set;}
public decimal? sustainbond {get;set;}
public decimal? juniorbondpay {get;set;}
public decimal? deferincometaxliab {get;set;}
public decimal? otherliab {get;set;}
public decimal? independentliab {get;set;}
public decimal? sumliab {get;set;}
public decimal? sharecapital {get;set;}
public decimal? capitalreserve {get;set;}
public decimal? otherequity {get;set;}
public decimal? preferredstock {get;set;}
public decimal? sustainabledebt {get;set;}
public decimal? otherequityother {get;set;}
public decimal? surplusreserve {get;set;}
public decimal? generalriskprepare {get;set;}
public decimal? retainedearning {get;set;}
public decimal? diffconversionfc {get;set;}
public decimal? sumparentequity {get;set;}
public decimal? minorityequity {get;set;}
public decimal? sumshequity {get;set;}
public decimal? sumliabshequity {get;set;}
}}
