using Newtonsoft.Json;
using System;
using System.Collections.Generic;
namespace NiceShot.Core.Models.Entities{
public class em_balancesheet_broker{
public long id {get;set;}
public string securitycode {get;set;}
public int reporttype {get;set;}
public int reportdatetype {get;set;}
public int type {get;set;}
public DateTime? reportdate {get;set;}
public string currency {get;set;}
public decimal? monetaryfund {get;set;}
public decimal? clientfund {get;set;}
public decimal? clientcreditfund {get;set;}
public decimal? settlementprovision {get;set;}
public decimal? clientprovision {get;set;}
public decimal? creditprovision {get;set;}
public decimal? lendfund {get;set;}
public decimal? marginoutfund {get;set;}
public decimal? marginoutsecurity {get;set;}
public decimal? fvaluefasset {get;set;}
public decimal? tradefasset {get;set;}
public decimal? definefvaluefasset {get;set;}
public decimal? derivefasset {get;set;}
public decimal? buysellbackfasset {get;set;}
public decimal? interestrec {get;set;}
public decimal? dividendrec {get;set;}
public decimal? receivables {get;set;}
public decimal? gdepositpay {get;set;}
public decimal? saleablefasset {get;set;}
public decimal? heldmaturityinv {get;set;}
public decimal? agencyassets {get;set;}
public decimal? ltequityinv {get;set;}
public decimal? estateinvest {get;set;}
public decimal? fixedasset {get;set;}
public decimal? constructionprogress {get;set;}
public decimal? intangibleasset {get;set;}
public decimal? seatfee {get;set;}
public decimal? goodwill {get;set;}
public decimal? deferincometaxasset {get;set;}
public decimal? otherasset {get;set;}
public decimal? sumasset {get;set;}
public decimal? stborrow {get;set;}
public decimal? pledgeborrow {get;set;}
public decimal? borrowfund {get;set;}
public decimal? fvaluefliab {get;set;}
public decimal? tradefliab {get;set;}
public decimal? definefvaluefliab {get;set;}
public decimal? derivefliab {get;set;}
public decimal? sellbuybackfasset {get;set;}
public decimal? agenttradesecurity {get;set;}
public decimal? cagenttradesecurity {get;set;}
public decimal? agentuwsecurity {get;set;}
public decimal? accountpay {get;set;}
public decimal? salarypay {get;set;}
public decimal? taxpay {get;set;}
public decimal? interestpay {get;set;}
public decimal? dividendpay {get;set;}
public decimal? shortfinancing {get;set;}
public decimal? agencyliab {get;set;}
public decimal? anticipateliab {get;set;}
public decimal? ltborrow {get;set;}
public decimal? bondpay {get;set;}
public decimal? deferincometaxliab {get;set;}
public decimal? otherliab {get;set;}
public decimal? sumliab {get;set;}
public decimal? sharecapital {get;set;}
public decimal? capitalreserve {get;set;}
public decimal? inventoryshare {get;set;}
public decimal? otherequity {get;set;}
public decimal? preferredstock {get;set;}
public decimal? sustainabledebt {get;set;}
public decimal? otherequityother {get;set;}
public decimal? surplusreserve {get;set;}
public decimal? generalriskprepare {get;set;}
public decimal? traderiskprepare {get;set;}
public decimal? retainedearning {get;set;}
public decimal? diffconversionfc {get;set;}
public decimal? sumparentequity {get;set;}
public decimal? minorityequity {get;set;}
public decimal? sumshequity {get;set;}
public decimal? sumliabshequity {get;set;}
}}
