using Newtonsoft.Json;
using System;
using System.Collections.Generic;
namespace NiceShot.Core.Models.Entities{
public class em_cashflow_insurance{
public long id {get;set;}
public string securitycode {get;set;}
public int reporttype {get;set;}
public int reportdatetype {get;set;}
public int type {get;set;}
public DateTime? reportdate {get;set;}
public string currency {get;set;}
public decimal? nideposit {get;set;}
public decimal? premiumrec {get;set;}
public decimal? netrirec {get;set;}
public decimal? niinsureddepositinv {get;set;}
public decimal? taxreturnrec {get;set;}
public decimal? nettradefassetrec {get;set;}
public decimal? intandcommrec {get;set;}
public decimal? nilendfund {get;set;}
public decimal? nddepositincbankfi {get;set;}
public decimal? nisellbuyback {get;set;}
public decimal? ndbuysellback {get;set;}
public decimal? otheroperaterec {get;set;}
public decimal? sumoperateflowin {get;set;}
public decimal? indemnitypay {get;set;}
public decimal? netripay {get;set;}
public decimal? ndlendfund {get;set;}
public decimal? nibuysellback {get;set;}
public decimal? ndsellbuyback {get;set;}
public decimal? niloanadvances {get;set;}
public decimal? intandcommpay {get;set;}
public decimal? divipay {get;set;}
public decimal? ndinsureddepositinv {get;set;}
public decimal? nidepositincbankfi {get;set;}
public decimal? employeepay {get;set;}
public decimal? taxpay {get;set;}
public decimal? nettradefassetpay {get;set;}
public decimal? otheroperatepay {get;set;}
public decimal? sumoperateflowout {get;set;}
public decimal? netoperatecashflow {get;set;}
public decimal? disposalinvrec {get;set;}
public decimal? invincomerec {get;set;}
public decimal? dispfilassetrec {get;set;}
public decimal? dispsubsidiaryrec {get;set;}
public decimal? buysellbackfassetrec {get;set;}
public decimal? otherinvrec {get;set;}
public decimal? suminvflowin {get;set;}
public decimal? invpay {get;set;}
public decimal? niinsuredpledgeloan {get;set;}
public decimal? buyfilassetpay {get;set;}
public decimal? buysubsidiarypay {get;set;}
public decimal? dispsubsidiarypay {get;set;}
public decimal? buysellbackfassetpay {get;set;}
public decimal? otherinvpay {get;set;}
public decimal? suminvflowout {get;set;}
public decimal? netinvcashflow {get;set;}
public decimal? acceptinvrec {get;set;}
public decimal? loanrec {get;set;}
public decimal? issuebondrec {get;set;}
public decimal? netsellbuybackfassetrec {get;set;}
public decimal? otherfinarec {get;set;}
public decimal? sumfinaflowin {get;set;}
public decimal? repaydebtpay {get;set;}
public decimal? diviprofitorintpay {get;set;}
public decimal? netsellbuybackfassetpay {get;set;}
public decimal? otherfinapay {get;set;}
public decimal? sumfinaflowout {get;set;}
public decimal? netfinacashflow {get;set;}
public decimal? effectexchangerate {get;set;}
public decimal? nicashequi {get;set;}
public decimal? cashequibeginning {get;set;}
public decimal? cashequiending {get;set;}
}}
