using Newtonsoft.Json;
using System;
using System.Collections.Generic;
namespace NiceShot.Core.Models.Entities{
public class em_cashflow_bank{
public long id {get;set;}
public string securitycode {get;set;}
public int reporttype {get;set;}
public int type {get;set;}
public DateTime? reportdate {get;set;}
public decimal? nideposit {get;set;}
public decimal? niclientdeposit {get;set;}
public decimal? nifideposit {get;set;}
public decimal? niborrowfromcbank {get;set;}
public decimal? nddepositincbankfi {get;set;}
public decimal? nddepositincbank {get;set;}
public decimal? nddepositinfi {get;set;}
public decimal? niborrowsellbuyback {get;set;}
public decimal? niborrowfund {get;set;}
public decimal? nisellbuybackfasset {get;set;}
public decimal? ndlendbuysellback {get;set;}
public decimal? ndlendfund {get;set;}
public decimal? ndbuysellbackfasset {get;set;}
public decimal? netcd {get;set;}
public decimal? nitradefliab {get;set;}
public decimal? ndtradefasset {get;set;}
public decimal? intandcommrec {get;set;}
public decimal? intrec {get;set;}
public decimal? commrec {get;set;}
public decimal? dispmassetrec {get;set;}
public decimal? cancelloanrec {get;set;}
public decimal? otheroperaterec {get;set;}
public decimal? sumoperateflowin {get;set;}
public decimal? niloanadvances {get;set;}
public decimal? ndborrowfromcbank {get;set;}
public decimal? nidepositincbankfi {get;set;}
public decimal? nidepositincbank {get;set;}
public decimal? nidepositinfi {get;set;}
public decimal? ndfideposit {get;set;}
public decimal? ndissuecd {get;set;}
public decimal? nilendsellbuyback {get;set;}
public decimal? nilendfund {get;set;}
public decimal? nibuysellbackfasset {get;set;}
public decimal? ndborrowsellbuyback {get;set;}
public decimal? ndborrowfund {get;set;}
public decimal? ndsellbuybackfasset {get;set;}
public decimal? nitradefasset {get;set;}
public decimal? ndtradefliab {get;set;}
public decimal? intandcommpay {get;set;}
public decimal? intpay {get;set;}
public decimal? commpay {get;set;}
public decimal? employeepay {get;set;}
public decimal? taxpay {get;set;}
public decimal? buyfinaleaseassetpay {get;set;}
public decimal? niaccountrec {get;set;}
public decimal? otheroperatepay {get;set;}
public decimal? sumoperateflowout {get;set;}
public decimal? netoperatecashflow {get;set;}
public decimal? disposalinvrec {get;set;}
public decimal? invincomerec {get;set;}
public decimal? diviorprofitrec {get;set;}
public decimal? dispfilassetrec {get;set;}
public decimal? dispsubsidiaryrec {get;set;}
public decimal? otherinvrec {get;set;}
public decimal? suminvflowin {get;set;}
public decimal? invpay {get;set;}
public decimal? buyfilassetpay {get;set;}
public decimal? getsubsidiarypay {get;set;}
public decimal? otherinvpay {get;set;}
public decimal? suminvflowout {get;set;}
public decimal? netinvcashflow {get;set;}
public decimal? issuebondrec {get;set;}
public decimal? issuejuniorbondrec {get;set;}
public decimal? issueotherbondrec {get;set;}
public decimal? otherfinarec {get;set;}
public decimal? acceptinvrec {get;set;}
public decimal? subsidiaryaccept {get;set;}
public decimal? issuecd {get;set;}
public decimal? addsharecapitalrec {get;set;}
public decimal? sumfinaflowin {get;set;}
public decimal? repaydebtpay {get;set;}
public decimal? bondintpay {get;set;}
public decimal? issuesharerec {get;set;}
public decimal? otherfinapay {get;set;}
public decimal? diviprofitorintpay {get;set;}
public decimal? sumfinaflowout {get;set;}
public decimal? netfinacashflow {get;set;}
public decimal? effectexchangerate {get;set;}
public decimal? nicashequi {get;set;}
public decimal? cashequibeginning {get;set;}
public decimal? cashequiending {get;set;}
}}
