using Newtonsoft.Json;
using System;
using System.Collections.Generic;
namespace NiceShot.Core.Models.Entities{
public class em_cf_common_v1{
public long id {get;set;}
public string secucode {get;set;}
public string security_code {get;set;}
public DateTime? report_date {get;set;}
public DateTime? notice_date {get;set;}
public DateTime? update_date {get;set;}
public decimal? sales_services {get;set;}
public decimal? deposit_interbank_add {get;set;}
public decimal? loan_pbc_add {get;set;}
public decimal? ofi_bf_add {get;set;}
public decimal? receive_origic_premium {get;set;}
public decimal? receive_reinsure_net {get;set;}
public decimal? insured_invest_add {get;set;}
public decimal? disposal_tfa_add {get;set;}
public decimal? receive_interest_commission {get;set;}
public decimal? borrow_fund_add {get;set;}
public decimal? loan_advance_reduce {get;set;}
public decimal? repo_business_add {get;set;}
public decimal? receive_tax_refund {get;set;}
public decimal? receive_other_operate {get;set;}
public decimal? operate_inflow_other {get;set;}
public decimal? operate_inflow_balance {get;set;}
public decimal? total_operate_inflow {get;set;}
public decimal? buy_services {get;set;}
public decimal? loan_advance_add {get;set;}
public decimal? pbc_interbank_add {get;set;}
public decimal? pay_origic_compensate {get;set;}
public decimal? pay_interest_commission {get;set;}
public decimal? pay_policy_bonus {get;set;}
public decimal? pay_staff_cash {get;set;}
public decimal? pay_all_tax {get;set;}
public decimal? pay_other_operate {get;set;}
public decimal? operate_outflow_other {get;set;}
public decimal? operate_outflow_balance {get;set;}
public decimal? total_operate_outflow {get;set;}
public decimal? operate_netcash_other {get;set;}
public decimal? operate_netcash_balance {get;set;}
public decimal? netcash_operate {get;set;}
public decimal? withdraw_invest {get;set;}
public decimal? receive_invest_income {get;set;}
public decimal? disposal_long_asset {get;set;}
public decimal? disposal_subsidiary_other {get;set;}
public decimal? reduce_pledge_timedeposits {get;set;}
public decimal? receive_other_invest {get;set;}
public decimal? invest_inflow_other {get;set;}
public decimal? invest_inflow_balance {get;set;}
public decimal? total_invest_inflow {get;set;}
public decimal? construct_long_asset {get;set;}
public decimal? invest_pay_cash {get;set;}
public decimal? pledge_loan_add {get;set;}
public decimal? obtain_subsidiary_other {get;set;}
public decimal? add_pledge_timedeposits {get;set;}
public decimal? pay_other_invest {get;set;}
public decimal? invest_outflow_other {get;set;}
public decimal? invest_outflow_balance {get;set;}
public decimal? total_invest_outflow {get;set;}
public decimal? invest_netcash_other {get;set;}
public decimal? invest_netcash_balance {get;set;}
public decimal? netcash_invest {get;set;}
public decimal? accept_invest_cash {get;set;}
public decimal? subsidiary_accept_invest {get;set;}
public decimal? receive_loan_cash {get;set;}
public decimal? issue_bond {get;set;}
public decimal? receive_other_finance {get;set;}
public decimal? finance_inflow_other {get;set;}
public decimal? finance_inflow_balance {get;set;}
public decimal? total_finance_inflow {get;set;}
public decimal? pay_debt_cash {get;set;}
public decimal? assign_dividend_porfit {get;set;}
public decimal? subsidiary_pay_dividend {get;set;}
public decimal? buy_subsidiary_equity {get;set;}
public decimal? pay_other_finance {get;set;}
public decimal? subsidiary_reduce_cash {get;set;}
public decimal? finance_outflow_other {get;set;}
public decimal? finance_outflow_balance {get;set;}
public decimal? total_finance_outflow {get;set;}
public decimal? finance_netcash_other {get;set;}
public decimal? finance_netcash_balance {get;set;}
public decimal? netcash_finance {get;set;}
public decimal? rate_change_effect {get;set;}
public decimal? cce_add_other {get;set;}
public decimal? cce_add_balance {get;set;}
public decimal? cce_add {get;set;}
public decimal? begin_cce {get;set;}
public decimal? end_cce_other {get;set;}
public decimal? end_cce_balance {get;set;}
public decimal? end_cce {get;set;}
public decimal? netprofit {get;set;}
public decimal? asset_impairment {get;set;}
public decimal? fa_ir_depr {get;set;}
public decimal? oilgas_biology_depr {get;set;}
public decimal? ir_depr {get;set;}
public decimal? ia_amortize {get;set;}
public decimal? lpe_amortize {get;set;}
public decimal? defer_income_amortize {get;set;}
public decimal? prepaid_expense_reduce {get;set;}
public decimal? accrued_expense_add {get;set;}
public decimal? disposal_longasset_loss {get;set;}
public decimal? fa_scrap_loss {get;set;}
public decimal? fairvalue_change_loss {get;set;}
public decimal? finance_expense {get;set;}
public decimal? invest_loss {get;set;}
public decimal? defer_tax {get;set;}
public decimal? dt_asset_reduce {get;set;}
public decimal? dt_liab_add {get;set;}
public decimal? predict_liab_add {get;set;}
public decimal? inventory_reduce {get;set;}
public decimal? operate_rece_reduce {get;set;}
public decimal? operate_payable_add {get;set;}
public decimal? other {get;set;}
public decimal? operate_netcash_othernote {get;set;}
public decimal? operate_netcash_balancenote {get;set;}
public decimal? netcash_operatenote {get;set;}
public decimal? debt_transfer_capital {get;set;}
public decimal? convert_bond_1year {get;set;}
public decimal? finlease_obtain_fa {get;set;}
public decimal? uninvolve_investfin_other {get;set;}
public decimal? end_cash {get;set;}
public decimal? begin_cash {get;set;}
public decimal? end_cash_equivalents {get;set;}
public decimal? begin_cash_equivalents {get;set;}
public decimal? cce_add_othernote {get;set;}
public decimal? cce_add_balancenote {get;set;}
public decimal? cce_addnote {get;set;}
public string opinion_type {get;set;}
public decimal? minority_interest {get;set;}
}}
