using Newtonsoft.Json;
using System;
using System.Collections.Generic;
namespace NiceShot.Core.Models.JsonObjects{
[JsonObject]
public class em_balancesheet_insurance_jo{
public string SECURITYCODE {get;set;}
public int REPORTTYPE {get;set;}
public int REPORTDATETYPE {get;set;}
public int TYPE {get;set;}
public string REPORTDATE {get;set;}
public string CURRENCY {get;set;}
public string MONETARYFUND {get;set;}
public string SETTLEMENTPROVISION {get;set;}
public string LENDFUND {get;set;}
public string FVALUEFASSET {get;set;}
public string TRADEFASSET {get;set;}
public string DEFINEFVALUEFASSET {get;set;}
public string DERIVEFASSET {get;set;}
public string BUYSELLBACKFASSET {get;set;}
public string INTERESTREC {get;set;}
public string PREMIUMREC {get;set;}
public string RIREC {get;set;}
public string RICONTACTRESERVEREC {get;set;}
public string UNDUERIRESERVEREC {get;set;}
public string CLAIMRIRESERVEREC {get;set;}
public string LIFERIRESERVEREC {get;set;}
public string LTHEALTHRIRESERVEREC {get;set;}
public string INSUREDPLEDGELOAN {get;set;}
public string LOANADVANCES {get;set;}
public string GDEPOSITPAY {get;set;}
public string CREDITORPLANINV {get;set;}
public string OTHERREC {get;set;}
public string TDEPOSIT {get;set;}
public string SALEABLEFASSET {get;set;}
public string HELDMATURITYINV {get;set;}
public string INVESTREC {get;set;}
public string ACCOUNTREC {get;set;}
public string LTEQUITYINV {get;set;}
public string CAPITALGDEPOSITPAY {get;set;}
public string ESTATEINVEST {get;set;}
public string FIXEDASSET {get;set;}
public string CONSTRUCTIONPROGRESS {get;set;}
public string INTANGIBLEASSET {get;set;}
public string GOODWILL {get;set;}
public string DEFERINCOMETAXASSET {get;set;}
public string OTHERASSET {get;set;}
public string INDEPENDENTASSET {get;set;}
public string SUMASSET {get;set;}
public string STBORROW {get;set;}
public string FIDEPOSIT {get;set;}
public string GDEPOSITREC {get;set;}
public string BORROWFUND {get;set;}
public string FVALUEFLIAB {get;set;}
public string TRADEFLIAB {get;set;}
public string DEFINEFVALUEFLIAB {get;set;}
public string DERIVEFLIAB {get;set;}
public string SELLBUYBACKFASSET {get;set;}
public string ACCEPTDEPOSIT {get;set;}
public string AGENTTRADESECURITY {get;set;}
public string ACCOUNTPAY {get;set;}
public string BILLPAY {get;set;}
public string ADVANCEREC {get;set;}
public string PREMIUMADVANCE {get;set;}
public string COMMPAY {get;set;}
public string RIPAY {get;set;}
public string SALARYPAY {get;set;}
public string TAXPAY {get;set;}
public string INTERESTPAY {get;set;}
public string DIVIDENDPAY {get;set;}
public string ANTICIPATELIAB {get;set;}
public string CLAIMPAY {get;set;}
public string POLICYDIVIPAY {get;set;}
public string OTHERPAY {get;set;}
public string INSUREDDEPOSITINV {get;set;}
public string CONTACTRESERVE {get;set;}
public string UNDUERESERVE {get;set;}
public string CLAIMRESERVE {get;set;}
public string LIFERESERVE {get;set;}
public string LTHEALTHRESERVE {get;set;}
public string LTBORROW {get;set;}
public string BONDPAY {get;set;}
public string PREFERSTOCBOND {get;set;}
public string SUSTAINBOND {get;set;}
public string JUNIORBONDPAY {get;set;}
public string DEFERINCOMETAXLIAB {get;set;}
public string OTHERLIAB {get;set;}
public string INDEPENDENTLIAB {get;set;}
public string SUMLIAB {get;set;}
public string SHARECAPITAL {get;set;}
public string CAPITALRESERVE {get;set;}
public string OTHEREQUITY {get;set;}
public string PREFERREDSTOCK {get;set;}
public string SUSTAINABLEDEBT {get;set;}
public string OTHEREQUITYOTHER {get;set;}
public string SURPLUSRESERVE {get;set;}
public string GENERALRISKPREPARE {get;set;}
public string RETAINEDEARNING {get;set;}
public string DIFFCONVERSIONFC {get;set;}
public string SUMPARENTEQUITY {get;set;}
public string MINORITYEQUITY {get;set;}
public string SUMSHEQUITY {get;set;}
public string SUMLIABSHEQUITY {get;set;}
}}
