using Newtonsoft.Json;
using System;
using System.Collections.Generic;
namespace NiceShot.Core.Models.JsonObjects{
[JsonObject]
public class em_balancesheet_broker_jo{
public string SECURITYCODE {get;set;}
public int REPORTTYPE {get;set;}
public int REPORTDATETYPE {get;set;}
public int TYPE {get;set;}
public string REPORTDATE {get;set;}
public string CURRENCY {get;set;}
public string MONETARYFUND {get;set;}
public string CLIENTFUND {get;set;}
public string CLIENTCREDITFUND {get;set;}
public string SETTLEMENTPROVISION {get;set;}
public string CLIENTPROVISION {get;set;}
public string CREDITPROVISION {get;set;}
public string LENDFUND {get;set;}
public string MARGINOUTFUND {get;set;}
public string MARGINOUTSECURITY {get;set;}
public string FVALUEFASSET {get;set;}
public string TRADEFASSET {get;set;}
public string DEFINEFVALUEFASSET {get;set;}
public string DERIVEFASSET {get;set;}
public string BUYSELLBACKFASSET {get;set;}
public string INTERESTREC {get;set;}
public string DIVIDENDREC {get;set;}
public string RECEIVABLES {get;set;}
public string GDEPOSITPAY {get;set;}
public string SALEABLEFASSET {get;set;}
public string HELDMATURITYINV {get;set;}
public string AGENCYASSETS {get;set;}
public string LTEQUITYINV {get;set;}
public string ESTATEINVEST {get;set;}
public string FIXEDASSET {get;set;}
public string CONSTRUCTIONPROGRESS {get;set;}
public string INTANGIBLEASSET {get;set;}
public string SEATFEE {get;set;}
public string GOODWILL {get;set;}
public string DEFERINCOMETAXASSET {get;set;}
public string OTHERASSET {get;set;}
public string SUMASSET {get;set;}
public string STBORROW {get;set;}
public string PLEDGEBORROW {get;set;}
public string BORROWFUND {get;set;}
public string FVALUEFLIAB {get;set;}
public string TRADEFLIAB {get;set;}
public string DEFINEFVALUEFLIAB {get;set;}
public string DERIVEFLIAB {get;set;}
public string SELLBUYBACKFASSET {get;set;}
public string AGENTTRADESECURITY {get;set;}
public string CAGENTTRADESECURITY {get;set;}
public string AGENTUWSECURITY {get;set;}
public string ACCOUNTPAY {get;set;}
public string SALARYPAY {get;set;}
public string TAXPAY {get;set;}
public string INTERESTPAY {get;set;}
public string DIVIDENDPAY {get;set;}
public string SHORTFINANCING {get;set;}
public string AGENCYLIAB {get;set;}
public string ANTICIPATELIAB {get;set;}
public string LTBORROW {get;set;}
public string BONDPAY {get;set;}
public string DEFERINCOMETAXLIAB {get;set;}
public string OTHERLIAB {get;set;}
public string SUMLIAB {get;set;}
public string SHARECAPITAL {get;set;}
public string CAPITALRESERVE {get;set;}
public string INVENTORYSHARE {get;set;}
public string OTHEREQUITY {get;set;}
public string PREFERREDSTOCK {get;set;}
public string SUSTAINABLEDEBT {get;set;}
public string OTHEREQUITYOTHER {get;set;}
public string SURPLUSRESERVE {get;set;}
public string GENERALRISKPREPARE {get;set;}
public string TRADERISKPREPARE {get;set;}
public string RETAINEDEARNING {get;set;}
public string DIFFCONVERSIONFC {get;set;}
public string SUMPARENTEQUITY {get;set;}
public string MINORITYEQUITY {get;set;}
public string SUMSHEQUITY {get;set;}
public string SUMLIABSHEQUITY {get;set;}
}}
