using Newtonsoft.Json;
using System;
using System.Collections.Generic;
namespace NiceShot.Core.Models.JsonObjects{
[JsonObject]
public class em_balancesheet_common_jo{
public string SECURITYCODE {get;set;}
public int REPORTTYPE {get;set;}
public int TYPE {get;set;}
public string REPORTDATE {get;set;}
public string MONETARYFUND {get;set;}
public string SETTLEMENTPROVISION {get;set;}
public string LENDFUND {get;set;}
public string FVALUEFASSET {get;set;}
public string TRADEFASSET {get;set;}
public string DEFINEFVALUEFASSET {get;set;}
public string BILLREC {get;set;}
public string ACCOUNTREC {get;set;}
public string ADVANCEPAY {get;set;}
public string PREMIUMREC {get;set;}
public string RIREC {get;set;}
public string RICONTACTRESERVEREC {get;set;}
public string INTERESTREC {get;set;}
public string DIVIDENDREC {get;set;}
public string OTHERREC {get;set;}
public string EXPORTREBATEREC {get;set;}
public string SUBSIDYREC {get;set;}
public string INTERNALREC {get;set;}
public string BUYSELLBACKFASSET {get;set;}
public string INVENTORY {get;set;}
public string CLHELDSALEASS {get;set;}
public string NONLASSETONEYEAR {get;set;}
public string OTHERLASSET {get;set;}
public string SUMLASSET {get;set;}
public string LOANADVANCES {get;set;}
public string SALEABLEFASSET {get;set;}
public string HELDMATURITYINV {get;set;}
public string LTREC {get;set;}
public string LTEQUITYINV {get;set;}
public string ESTATEINVEST {get;set;}
public string FIXEDASSET {get;set;}
public string CONSTRUCTIONPROGRESS {get;set;}
public string CONSTRUCTIONMATERIAL {get;set;}
public string LIQUIDATEFIXEDASSET {get;set;}
public string PRODUCTBIOLOGYASSET {get;set;}
public string OILGASASSET {get;set;}
public string INTANGIBLEASSET {get;set;}
public string DEVELOPEXP {get;set;}
public string GOODWILL {get;set;}
public string LTDEFERASSET {get;set;}
public string DEFERINCOMETAXASSET {get;set;}
public string OTHERNONLASSET {get;set;}
public string SUMNONLASSET {get;set;}
public string SUMASSET {get;set;}
public string STBORROW {get;set;}
public string BORROWFROMCBANK {get;set;}
public string DEPOSIT {get;set;}
public string BORROWFUND {get;set;}
public string FVALUEFLIAB {get;set;}
public string TRADEFLIAB {get;set;}
public string DEFINEFVALUEFLIAB {get;set;}
public string BILLPAY {get;set;}
public string ACCOUNTPAY {get;set;}
public string ADVANCERECEIVE {get;set;}
public string SELLBUYBACKFASSET {get;set;}
public string COMMPAY {get;set;}
public string SALARYPAY {get;set;}
public string TAXPAY {get;set;}
public string INTERESTPAY {get;set;}
public string DIVIDENDPAY {get;set;}
public string RIPAY {get;set;}
public string INTERNALPAY {get;set;}
public string OTHERPAY {get;set;}
public string ANTICIPATELLIAB {get;set;}
public string CONTACTRESERVE {get;set;}
public string AGENTTRADESECURITY {get;set;}
public string AGENTUWSECURITY {get;set;}
public string DEFERINCOMEONEYEAR {get;set;}
public string STBONDREC {get;set;}
public string CLHELDSALELIAB {get;set;}
public string NONLLIABONEYEAR {get;set;}
public string OTHERLLIAB {get;set;}
public string SUMLLIAB {get;set;}
public string LTBORROW {get;set;}
public string BONDPAY {get;set;}
public string PREFERSTOCBOND {get;set;}
public string SUSTAINBOND {get;set;}
public string LTACCOUNTPAY {get;set;}
public string LTSALARYPAY {get;set;}
public string SPECIALPAY {get;set;}
public string ANTICIPATELIAB {get;set;}
public string DEFERINCOME {get;set;}
public string DEFERINCOMETAXLIAB {get;set;}
public string OTHERNONLLIAB {get;set;}
public string SUMNONLLIAB {get;set;}
public string SUMLIAB {get;set;}
public string SHARECAPITAL {get;set;}
public string OTHEREQUITY {get;set;}
public string PREFERREDSTOCK {get;set;}
public string SUSTAINABLEDEBT {get;set;}
public string OTHEREQUITYOTHER {get;set;}
public string CAPITALRESERVE {get;set;}
public string INVENTORYSHARE {get;set;}
public string SPECIALRESERVE {get;set;}
public string SURPLUSRESERVE {get;set;}
public string GENERALRISKPREPARE {get;set;}
public string UNCONFIRMINVLOSS {get;set;}
public string RETAINEDEARNING {get;set;}
public string PLANCASHDIVI {get;set;}
public string DIFFCONVERSIONFC {get;set;}
public string SUMPARENTEQUITY {get;set;}
public string MINORITYEQUITY {get;set;}
public string SUMSHEQUITY {get;set;}
public string SUMLIABSHEQUITY {get;set;}
}}
