using Newtonsoft.Json;
using System;
using System.Collections.Generic;
namespace NiceShot.Core.Models.JsonObjects
{

    public class em_bal_common_v1_jo_list
    {
        public List<em_bal_common_v1_jo> data { get; set; }
    }

    [JsonObject]
    public class em_bal_common_v1_jo
    {
        public string secucode { get; set; }
        public string security_code { get; set; }
        public string report_date { get; set; }
        public string notice_date { get; set; }
        public string update_date { get; set; }
        public string accept_deposit_interbank { get; set; }
        public string accounts_payable { get; set; }
        public string accounts_rece { get; set; }
        public string accrued_expense { get; set; }
        public string advance_receivables { get; set; }
        public string agent_trade_security { get; set; }
        public string agent_underwrite_security { get; set; }
        public string amortize_cost_finasset { get; set; }
        public string amortize_cost_finliab { get; set; }
        public string amortize_cost_ncfinasset { get; set; }
        public string amortize_cost_ncfinliab { get; set; }
        public string appoint_fvtpl_finasset { get; set; }
        public string appoint_fvtpl_finliab { get; set; }
        public string asset_balance { get; set; }
        public string asset_other { get; set; }
        public string assign_cash_dividend { get; set; }
        public string available_sale_finasset { get; set; }
        public string bond_payable { get; set; }
        public string borrow_fund { get; set; }
        public string buy_resale_finasset { get; set; }
        public string capital_reserve { get; set; }
        public string cip { get; set; }
        public string consumptive_biological_asset { get; set; }
        public string contract_asset { get; set; }
        public string contract_liab { get; set; }
        public string convert_diff { get; set; }
        public string creditor_invest { get; set; }
        public string current_asset_balance { get; set; }
        public string current_asset_other { get; set; }
        public string current_liab_balance { get; set; }
        public string current_liab_other { get; set; }
        public string defer_income { get; set; }
        public string defer_income_1year { get; set; }
        public string defer_tax_asset { get; set; }
        public string defer_tax_liab { get; set; }
        public string derive_finasset { get; set; }
        public string derive_finliab { get; set; }
        public string develop_expense { get; set; }
        public string div_holdsale_asset { get; set; }
        public string div_holdsale_liab { get; set; }
        public string dividend_payable { get; set; }
        public string dividend_rece { get; set; }
        public string equity_balance { get; set; }
        public string equity_other { get; set; }
        public string export_refund_rece { get; set; }
        public string fee_commission_payable { get; set; }
        public string fin_fund { get; set; }
        public string finance_rece { get; set; }
        public string fixed_asset { get; set; }
        public string fixed_asset_disposal { get; set; }
        public string fvtoci_finasset { get; set; }
        public string fvtoci_ncfinasset { get; set; }
        public string fvtpl_finasset { get; set; }
        public string fvtpl_finliab { get; set; }
        public string general_risk_reserve { get; set; }
        public string goodwill { get; set; }
        public string hold_maturity_invest { get; set; }
        public string holdsale_asset { get; set; }
        public string holdsale_liab { get; set; }
        public string insurance_contract_reserve { get; set; }
        public string intangible_asset { get; set; }
        public string interest_payable { get; set; }
        public string interest_rece { get; set; }
        public string internal_payable { get; set; }
        public string internal_rece { get; set; }
        public string inventory { get; set; }
        public string invest_realestate { get; set; }
        public string lease_liab { get; set; }
        public string lend_fund { get; set; }
        public string liab_balance { get; set; }
        public string liab_equity_balance { get; set; }
        public string liab_equity_other { get; set; }
        public string liab_other { get; set; }
        public string loan_advance { get; set; }
        public string loan_pbc { get; set; }
        public string long_equity_invest { get; set; }
        public string long_loan { get; set; }
        public string long_payable { get; set; }
        public string long_prepaid_expense { get; set; }
        public string long_rece { get; set; }
        public string long_staffsalary_payable { get; set; }
        public string minority_equity { get; set; }
        public string monetaryfunds { get; set; }
        public string noncurrent_asset_1year { get; set; }
        public string noncurrent_asset_balance { get; set; }
        public string noncurrent_asset_other { get; set; }
        public string noncurrent_liab_1year { get; set; }
        public string noncurrent_liab_balance { get; set; }
        public string noncurrent_liab_other { get; set; }
        public string note_accounts_payable { get; set; }
        public string note_accounts_rece { get; set; }
        public string note_payable { get; set; }
        public string note_rece { get; set; }
        public string oil_gas_asset { get; set; }
        public string other_compre_income { get; set; }
        public string other_creditor_invest { get; set; }
        public string other_current_asset { get; set; }
        public string other_current_liab { get; set; }
        public string other_equity_invest { get; set; }
        public string other_equity_other { get; set; }
        public string other_equity_tool { get; set; }
        public string other_noncurrent_asset { get; set; }
        public string other_noncurrent_finasset { get; set; }
        public string other_noncurrent_liab { get; set; }
        public string other_payable { get; set; }
        public string other_rece { get; set; }
        public string parent_equity_balance { get; set; }
        public string parent_equity_other { get; set; }
        public string perpetual_bond { get; set; }
        public string perpetual_bond_paybale { get; set; }
        public string predict_current_liab { get; set; }
        public string predict_liab { get; set; }
        public string preferred_shares { get; set; }
        public string preferred_shares_paybale { get; set; }
        public string premium_rece { get; set; }
        public string prepayment { get; set; }
        public string productive_biology_asset { get; set; }
        public string project_material { get; set; }
        public string rc_reserve_rece { get; set; }
        public string reinsure_payable { get; set; }
        public string reinsure_rece { get; set; }
        public string sell_repo_finasset { get; set; }
        public string settle_excess_reserve { get; set; }
        public string share_capital { get; set; }
        public string short_bond_payable { get; set; }
        public string short_fin_payable { get; set; }
        public string short_loan { get; set; }
        public string special_payable { get; set; }
        public string special_reserve { get; set; }
        public string staff_salary_payable { get; set; }
        public string subsidy_rece { get; set; }
        public string surplus_reserve { get; set; }
        public string tax_payable { get; set; }
        public string total_assets { get; set; }
        public string total_current_assets { get; set; }
        public string total_current_liab { get; set; }
        public string total_equity { get; set; }
        public string total_liab_equity { get; set; }
        public string total_liabilities { get; set; }
        public string total_noncurrent_assets { get; set; }
        public string total_noncurrent_liab { get; set; }
        public string total_other_payable { get; set; }
        public string total_other_rece { get; set; }
        public string total_parent_equity { get; set; }
        public string trade_finasset { get; set; }
        public string trade_finasset_notfvtpl { get; set; }
        public string trade_finliab { get; set; }
        public string trade_finliab_notfvtpl { get; set; }
        public string treasury_shares { get; set; }
        public string unassign_rpofit { get; set; }
        public string unconfirm_invest_loss { get; set; }
        public string useright_asset { get; set; }
        public string opinion_type { get; set; }
    }
}
